stages:
  - test
  - build
  - deploy

test backend:
  stage: test
  image: golang:1.11
  tags:
    - docker
  script:
    - ./pipelines.sh test backend
  cache:
    key: backend
    paths:
      - backend/vendor
    policy: pull-push

test frontend:
  stage: test
  image: node:11
  tags:
    - docker
  script:
    - ./pipelines.sh test frontend
  cache:
    key: backend
    paths:
      - frontend/.yarn-cache
    policy: pull-push

build auth:
  stage: build
  image: docker:stable
  tags:
    - docker
  services:
    - docker:dind
  script:
    - ./pipelines.sh build auth
  cache:
    untracked: false
    key: auth
    paths:
      - auth/vendor
    policy: pull

build backend:
  stage: build
  image: docker:stable
  tags:
    - docker
  services:
    - docker:dind
  script:
    - ./pipelines.sh build backend
  cache:
    untracked: false
    key: backend
    paths:
      - backend/vendor
    policy: pull

build frontend:
  stage: build
  image: docker:stable
  tags:
    - docker
  services:
    - docker:dind
  script:
    - ./pipelines.sh build frontend
  cache:
    untracked: false
    key: frontend
    paths:
      - frontend/.yarn-cache
    policy: pull

deploy auth:
  stage: deploy
  image: google/cloud-sdk
  tags:
    - docker
  services:
    - docker:dind
  script:
    - ./pipelines.sh deploy auth
  only:
    refs:
      - tags
