stages:
  - test
  - build

test backend:
  stage: test
  image: golang:1.11
  script:
    - ./pipelines.sh test backend

build backend:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - ./pipelines.sh build backend
