stages:
  - test and build
  - deploy

include:
  template: Dependency-Scanning.gitlab-ci.yml

dependency_scanning:
  stage: test and build

test backend:
  stage: test and build
  image: golang:1.12
  tags:
    - docker
  script:
    - ./pipelines.sh test backend
  cache:
    key: backend
    paths:
      - /go/pkg/mod
    policy: pull-push

test frontend:
  stage: test and build
  image: node:11
  tags:
    - docker
  script:
    - ./pipelines.sh test frontend
  dependencies: []

build backend:
  stage: test and build
  image: google/cloud-sdk:alpine
  tags:
    - docker
  script:
    - ./pipelines.sh build backend
  dependencies: []

deploy backend:
  stage: deploy
  image: google/cloud-sdk:slim
  tags:
    - docker
  script:
    - ./pipelines.sh deploy backend
  only:
    refs:
      - master
  dependencies: []
  environment:
    name: production
