stages:
  - test
  - build
  - deploy

test auth:
  stage: test
  image: golang:1.12
  tags:
    - docker
  script:
    - ./pipelines.sh test auth
  cache:
    key: auth
    paths:
      - /go/pkg/mod
    policy: pull-push
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - auth/vendor


test backend:
  stage: test
  image: golang:1.12
  tags:
    - docker
  script:
    - ./pipelines.sh test backend
  cache:
    key: backend
    paths:
      - /go/pkg/mod
    policy: pull-push
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - backend/vendor

test frontend:
  stage: test
  image: node:11
  tags:
    - docker
  script:
    - ./pipelines.sh test frontend
  cache:
    key: frontend
    paths:
      - frontend/.yarn-cache
    policy: pull-push

build auth:
  stage: build
  image: docker:stable
  tags:
    - docker
  services:
    - docker:dind
  script:
    - ./pipelines.sh build auth
  dependencies:
    - test auth

build backend:
  stage: build
  image: docker:stable
  tags:
    - docker
  services:
    - docker:dind
  script:
    - ./pipelines.sh build backend
  dependencies:
    - test backend

build frontend:
  stage: build
  image: docker:stable
  tags:
    - docker
  services:
    - docker:dind
  script:
    - ./pipelines.sh build frontend
  cache:
    untracked: false
    key: frontend
    paths:
      - frontend/.yarn-cache
    policy: pull

deploy auth:
  stage: deploy
  image: google/cloud-sdk
  tags:
    - docker
  services:
    - docker:dind
  script:
    - ./pipelines.sh deploy auth
  only:
    refs:
      - tags
