stages:
  - test
  - build
  - deploy

test backend:
  stage: test
  image: golang:1.12
  tags:
    - docker
  script:
    - ./pipelines.sh test backend
  cache:
    key: backend
    paths:
      - /go/pkg/mod
    policy: pull-push

test frontend:
  stage: test
  image: node:11
  tags:
    - docker
  script:
    - ./pipelines.sh test frontend
  dependencies: []

build backend:
  stage: build
  image: google/cloud-sdk:alpine
  tags:
    - docker
  script:
    - ./pipelines.sh build backend
  dependencies: []

build frontend:
  stage: build
  image: google/cloud-sdk:alpine
  tags:
    - docker
  script:
    - ./pipelines.sh build frontend

deploy frontend:
  stage: deploy
  image: google/cloud-sdk:alpine
  tags:
    - docker
  script:
    - ./pipelines.sh deploy frontend
  only:
    refs:
      - master
  dependencies: []
  environment:
    name: production

deploy backend:
  stage: deploy
  image: google/cloud-sdk:alpine
  tags:
    - docker
  script:
    - ./pipelines.sh deploy backend
  only:
    refs:
      - master
  dependencies: []
  environment:
    name: production
