version: "3"

services:
  db:
    image: cockroachdb/cockroach
    volumes:
      - roachdb:/cockroach/cockroach-data
    command:
      - start
      - --insecure
    ports:
      - 26257:26257
      - 8080:8080

volumes:
  roachdb:
