---


version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

    volumes:
      - ..:/workspace
    command: sleep infinity

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: postgres
      POSTGRES_DB: gitreleased
    ports:
      - 5432:5432

